apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: ksops-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
files:
  - ansible/aap.yaml
  - ansible/certs.yaml
  - arc/arcrunners.yaml
  - arc/dindsystem.yaml
