---
apiVersion: v1
kind: Namespace
metadata:
  name: arc-systems
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc
  namespace: openshift-gitops
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
  project: default
  source:
    chart: gha-runner-scale-set-controller
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: 0.11.0
    helm:
      releaseName: arc
  destination:
    server: "https://kubernetes.default.svc"
    namespace: arc-systems