---
apiVersion: v1
kind: Namespace
metadata:
  name: arc-dind-runners
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: docker-daemon-config
    namespace: arc-dind-runners
    annotations:
        kustomize.config.k8s.io/behavior: merge
data:
  daemon.json: '{"registry-mirrors": ["http://registry.docker-registry.svc:5000"], "insecure-registries": ["registry.docker-registry.svc:5000", "registry.docker-registry.svc.cluster.local:5000", "image-registry.openshift-image-registry.svc:5000", "image-registry.openshift-image-registry.svc.cluster.local:5000", "default-route-openshift-image-registry.apps.makeitwork.cloud"]}'
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: arc-dind
  namespace: arc-dind-runners
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  replicas: 1
  template:
    spec:
      resources:
        limits:
          memory: 8Gi
        requests:
          memory: 100Mi
      image: summerwind/actions-runner-dind
      ephemeral: false
      dockerdWithinRunnerContainer: true
      organization: makeitworkcloud
      labels:
        - arc-dind
      volumeMounts:
        - mountPath: /etc/docker/daemon.json
          name: daemon-config-volume
          subPath: daemon.json
        - mountPath: /var/lib/docker
          name: var-lib-docker
      volumes:
        - name: daemon-config-volume
          configMap:
            name: docker-daemon-config
            items:
              - key: daemon.json
                path: daemon.json
        - name: var-lib-docker
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 50Gi
