---
apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: aap
  namespace: aap
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  route_tls_termination_mechanism: Edge
  no_log: true
  api:
    log_level: INFO
    replicas: 1
  ingress_type: Route
  route_host: ansible.makeitwork.cloud
  route_tls_secret: makeitwork-tls
